# Generated by Django 3.0.3 on 2020-02-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyjournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
